import numpy as np
import matplotlib.pyplot as plt

# Load the 3 different data files generated by C++
try:
    phantom = np.loadtxt("build/phantom.csv", delimiter=",")
    sinogram = np.loadtxt("build/sinogram.csv", delimiter=",")
    reconstructed = np.loadtxt("build/reconstructed.csv", delimiter=",")
except FileNotFoundError:
    print("Error: CSV files not found! Make sure you are in the directory where the C++ code was executed.")
    exit()

fig, axs = plt.subplots(1, 3, figsize=(16, 5))

# 1. Original Object (X-Y Axis)
axs[0].imshow(phantom, cmap='gray')
axs[0].set_title("Original Object (Phantom from C++)")
axs[0].set_xlabel("X (Pixels)")
axs[0].set_ylabel("Y (Pixels)")

# 2. Scan Data (Angle-Ray Axis - Sinogram)
axs[1].imshow(sinogram, cmap='viridis', aspect='auto')
axs[1].set_title("Sinogram (Raw Data)")
axs[1].set_xlabel("Ray (Fan) Index")
axs[1].set_ylabel("Rotation Angle (Degrees)")

# 3. Back Projection (X-Y Axis - Reconstructed with FBP)
axs[2].imshow(reconstructed, cmap='gray', vmin=0, vmax=1)
axs[2].set_title("Filtered Back Projection (Result)")
axs[2].set_xlabel("X (Pixels)")
axs[2].set_ylabel("Y (Pixels)")

plt.tight_layout()
plt.show()